### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by harvxie** [Gaider10/BookDupe#1]
I was on a server and it was displaying the 'book is too large' message, so I decided to try it on a single-player world. No use at all, it just gave the 'if you can see this, it didn't work' book to me.

**Comment by Gaider10** [comment]
My mod doesn't have 'if you can see this, it didn't work' feature. This bug was fixed on paper several hours after it was leaked, and it never worked on spigot. In singleplayer it works, it just doesn't kick you and you need to leave yorself. Currently it only works on vanilla and fabric servers, or 1.15 paper servers.
